# Generated by Django 6.0.5 on 2026-05-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="routineexercise",
            name="category",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="routineexercise",
            name="instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="routineexercise",
            name="primary_muscle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="routineexercise",
            name="secondary_muscle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="routineexercise",
            name="sets_data",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
